"use client";

import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { useApp } from "@/components/providers";

/** A "letter of the day" generated by the Python content-api (falls back locally). */
export default function NoteOfDay() {
  const { t, lang } = useApp();
  const [note, setNote] = useState<string>("");

  useEffect(() => {
    // deterministic local fallback (same note per day)
    const day = Math.floor(Date.now() / 864e5);
    setNote(t.love_notes[day % t.love_notes.length]);

    fetch(`/api/note?lang=${lang}`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => d?.note && setNote(d.note))
      .catch(() => {});
  }, [t, lang]);

  if (!note) return null;
  return (
    <div className="mx-auto w-full max-w-2xl px-5">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
        className="glass rounded-full px-6 py-3 text-center"
      >
        <span className="font-script mr-2 text-lg text-rose">{t.note_of_day}:</span>
        <span className="text-sm italic text-cream">{note}</span>
      </motion.div>
    </div>
  );
}
